// ASSUMED CONTRACT — not generated from the real rate limiter project.
//
// This mirrors a typical GCRA rate limiter gRPC API (single Allow RPC,
// key in, allowed/retry-after out). If your existing rate limiter service
// exposes a different method or message shape, replace this file with its
// real .proto (or copy it in from that project) and regenerate — this is
// the only file that should need to change; internal/ratelimit.Limiter
// and everything above it don't know or care about the wire format.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/ratelimit/v1/ratelimit.proto

package ratelimitv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AllowRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key identifies the caller/resource being limited — an API key's
	// owner ID for authenticated routes, a client IP for anonymous ones.
	Key           string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowRequest) Reset() {
	*x = AllowRequest{}
	mi := &file_api_ratelimit_v1_ratelimit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowRequest) ProtoMessage() {}

func (x *AllowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_ratelimit_v1_ratelimit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowRequest.ProtoReflect.Descriptor instead.
func (*AllowRequest) Descriptor() ([]byte, []int) {
	return file_api_ratelimit_v1_ratelimit_proto_rawDescGZIP(), []int{0}
}

func (x *AllowRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type AllowResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Allowed bool                   `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// retry_after_ms is set when allowed is false: how long the caller
	// should wait before retrying, in milliseconds.
	RetryAfterMs  int64 `protobuf:"varint,2,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllowResponse) Reset() {
	*x = AllowResponse{}
	mi := &file_api_ratelimit_v1_ratelimit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllowResponse) ProtoMessage() {}

func (x *AllowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_ratelimit_v1_ratelimit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllowResponse.ProtoReflect.Descriptor instead.
func (*AllowResponse) Descriptor() ([]byte, []int) {
	return file_api_ratelimit_v1_ratelimit_proto_rawDescGZIP(), []int{1}
}

func (x *AllowResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *AllowResponse) GetRetryAfterMs() int64 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

var File_api_ratelimit_v1_ratelimit_proto protoreflect.FileDescriptor

const file_api_ratelimit_v1_ratelimit_proto_rawDesc = "" +
	"\n" +
	" api/ratelimit/v1/ratelimit.proto\x12\fratelimit.v1\" \n" +
	"\fAllowRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"O\n" +
	"\rAllowResponse\x12\x18\n" +
	"\aallowed\x18\x01 \x01(\bR\aallowed\x12$\n" +
	"\x0eretry_after_ms\x18\x02 \x01(\x03R\fretryAfterMs2O\n" +
	"\vRateLimiter\x12@\n" +
	"\x05Allow\x12\x1a.ratelimit.v1.AllowRequest\x1a\x1b.ratelimit.v1.AllowResponseBDZBurlshortener/internal/ratelimit/grpcclient/ratelimitv1;ratelimitv1b\x06proto3"

var (
	file_api_ratelimit_v1_ratelimit_proto_rawDescOnce sync.Once
	file_api_ratelimit_v1_ratelimit_proto_rawDescData []byte
)

func file_api_ratelimit_v1_ratelimit_proto_rawDescGZIP() []byte {
	file_api_ratelimit_v1_ratelimit_proto_rawDescOnce.Do(func() {
		file_api_ratelimit_v1_ratelimit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_ratelimit_v1_ratelimit_proto_rawDesc), len(file_api_ratelimit_v1_ratelimit_proto_rawDesc)))
	})
	return file_api_ratelimit_v1_ratelimit_proto_rawDescData
}

var file_api_ratelimit_v1_ratelimit_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_ratelimit_v1_ratelimit_proto_goTypes = []any{
	(*AllowRequest)(nil),  // 0: ratelimit.v1.AllowRequest
	(*AllowResponse)(nil), // 1: ratelimit.v1.AllowResponse
}
var file_api_ratelimit_v1_ratelimit_proto_depIdxs = []int32{
	0, // 0: ratelimit.v1.RateLimiter.Allow:input_type -> ratelimit.v1.AllowRequest
	1, // 1: ratelimit.v1.RateLimiter.Allow:output_type -> ratelimit.v1.AllowResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_ratelimit_v1_ratelimit_proto_init() }
func file_api_ratelimit_v1_ratelimit_proto_init() {
	if File_api_ratelimit_v1_ratelimit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_ratelimit_v1_ratelimit_proto_rawDesc), len(file_api_ratelimit_v1_ratelimit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_ratelimit_v1_ratelimit_proto_goTypes,
		DependencyIndexes: file_api_ratelimit_v1_ratelimit_proto_depIdxs,
		MessageInfos:      file_api_ratelimit_v1_ratelimit_proto_msgTypes,
	}.Build()
	File_api_ratelimit_v1_ratelimit_proto = out.File
	file_api_ratelimit_v1_ratelimit_proto_goTypes = nil
	file_api_ratelimit_v1_ratelimit_proto_depIdxs = nil
}
